'use strict';
/*
  bookingCapture.js — resolve a Google Flights "booking" deep link.

  Google Flights' booking page URL carries two protobuf parameters (tfs +
  tfu) that pin the result to a specific flight + fare. Those tokens can't
  be constructed offline — they are generated by Google when the user
  clicks a flight in the result list. So we drive Playwright through that
  same path: open the q= search → click the matching anchor → wait for
  the booking URL → return it.

  This is essentially the same flow as fli's capture_booking_token, but
  written in JS so it reuses the Playwright Chromium already installed
  for the scraper fallback.
*/

const { chromium } = require('playwright');

// ─── Singleton browser (separate from scraper's) ──────────────────
let _browser = null;
async function getBrowser() {
  if (_browser) {
    try { await _browser.version(); return _browser; } catch { _browser = null; }
  }
  _browser = await chromium.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-dev-shm-usage', '--disable-blink-features=AutomationControlled'],
  });
  _browser.on('disconnected', () => { _browser = null; });
  return _browser;
}

// Convert "HH:MM" (24h) → "H:MM AM/PM" matching Google's aria-label.
function to12h(hhmm) {
  const m = String(hhmm).match(/^(\d{1,2}):(\d{2})$/);
  if (!m) return hhmm;
  let h = parseInt(m[1], 10); const mm = m[2];
  const ap = h >= 12 ? 'PM' : 'AM';
  h = h % 12; if (h === 0) h = 12;
  return `${h}:${mm} ${ap}`;
}

// ─── Cache: route + flight → resolved URL ─────────────────────────
const CACHE     = new Map();
const CACHE_TTL = 30 * 60 * 1000;   // 30 min
function cacheKey(p) { return `${p.origin}|${p.dest}|${p.date}|${p.depTime}`; }

// ─── Public entry point ───────────────────────────────────────────
async function captureBookingUrl({ origin, dest, date, depTime, currency = 'EUR' }) {
  const key = cacheKey({ origin, dest, date, depTime });
  const hit = CACHE.get(key);
  if (hit && Date.now() - hit.at < CACHE_TTL) {
    console.log(`[booking] ⚡ cache hit ${key}`);
    return hit.url;
  }

  const browser = await getBrowser();
  const ctx = await browser.newContext({
    userAgent:
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
      '(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
    locale: 'en-US',
    timezoneId: 'Europe/London',
    viewport: { width: 1366, height: 800 },
    extraHTTPHeaders: { 'Accept-Language': 'en-US,en;q=0.9' },
  });

  await ctx.addInitScript(`
    Object.defineProperty(navigator, 'webdriver',  { get: () => undefined });
    Object.defineProperty(navigator, 'languages',  { get: () => ['en-US','en'] });
    window.chrome = { runtime: {} };
  `);

  // Block images/media/fonts to speed up the navigation.
  await ctx.route('**/*', route => {
    const t = route.request().resourceType();
    if (['image', 'media', 'font'].includes(t)) return route.abort();
    route.continue();
  });

  const page = await ctx.newPage();
  // Explicit "one way" so Google doesn't auto-pair a return date — without
  // this, selecting the outbound lands on a "Choose return flight" page.
  const searchUrl =
    `https://www.google.com/travel/flights?hl=en&curr=${currency}&gl=US&q=` +
    encodeURIComponent(`Flights from ${origin} to ${dest} on ${date} one way`);

  console.log(`[booking] ${origin}→${dest} ${date} @ ${depTime} → capturing`);

  try {
    await page.goto(searchUrl, { timeout: 35000, waitUntil: 'load' });

    // GDPR consent page intercepts on EU IPs — accept and wait for redirect.
    if (page.url().includes('consent.google.com')) {
      try {
        // Use the visible "Accept all" button.
        await page.locator('button[aria-label="Accept all"]').first().click({ timeout: 5000 });
        await page.waitForURL(u => !u.toString().includes('consent.google.com'), { timeout: 15000 });
      } catch (e) {
        console.warn(`[booking] consent click failed: ${e.message.slice(0,60)}`);
      }
      // Re-navigate to the search if needed.
      if (!page.url().includes('/travel/flights')) {
        await page.goto(searchUrl, { timeout: 30000, waitUntil: 'load' });
      }
    }

    // Google Flights UI (Nov 2025): two-step selection.
    //   1) Click the "Flight details. Leaves … at <dep> on …" toggle to
    //      expand the row for the desired flight.
    //   2) Inside the expanded row a "Select flight" button becomes visible.
    //      Clicking it navigates to a URL carrying the tfs + tfu protobuf
    //      tokens — the deep link to the booking flow for that flight.
    await page.waitForSelector('button[aria-label*="Flight details. Leaves"]', { timeout: 25000 });

    const matchToken = `at ${to12h(depTime)} on`;
    const detailsBtn = page.locator(`button[aria-label*="${matchToken}"]`).first();
    if (!(await detailsBtn.count())) {
      throw new Error(`no flight matched "${matchToken}"`);
    }
    await detailsBtn.click({ timeout: 10000 });

    // Wait for the in-row "Select flight" button to become visible.
    await page.waitForSelector('button:has-text("Select flight"):visible', { timeout: 12000 });
    await page.locator('button:has-text("Select flight"):visible').first().click({ timeout: 8000 });

    // Wait for navigation to a URL carrying tfs + tfu. Google may land on
    // /booking (final page) or /search (intermediate w/ tokens) — both are
    // flight-specific deep links the user can complete from.
    await page.waitForURL(u => {
      const s = u.toString();
      return /\/travel\/flights\/(booking|search)\?/.test(s) && s.includes('tfs=') && s.includes('tfu=');
    }, { timeout: 20000 });

    const url = page.url();
    CACHE.set(key, { at: Date.now(), url });
    console.log(`[booking] ✓ captured (${url.length} chars)`);
    return url;
  } finally {
    await ctx.close().catch(() => {});
  }
}

module.exports = { captureBookingUrl };
